# Generated by Django 5.2.9 on 2026-01-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='votes',
            new_name='voters',
        ),
    ]
