# Generated by Django 5.2.9 on 2026-01-03 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_post_voters_post_down_voters_post_up_voters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='down_voters',
            field=models.ManyToManyField(blank=True, null=True, related_name='downvoted_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
