# Generated by Django 5.2.4 on 2025-07-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
