# Generated by Django 5.2.9 on 2025-12-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='members_count',
            field=models.IntegerField(default=0),
        ),
    ]
