# Generated by Django 5.2.4 on 2025-07-30 06:00

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, max_length=250, populate_from='name', unique=True),
        ),
    ]
