# Generated by Django 5.2.9 on 2025-12-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_members_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='members_count',
        ),
    ]
