# Generated by Django 5.2.4 on 2025-07-27 01:51

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, populate_from='name', unique=True),
        ),
    ]
