# Generated by Django 5.2.9 on 2025-12-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_remove_community_members_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='members_count',
            field=models.IntegerField(default=0),
        ),
    ]
