# Generated by Django 5.2.9 on 2025-12-29 19:34

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_community_members_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='community_name', unique=True),
        ),
    ]
