# Generated by Django 5.2.9 on 2025-12-31 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_community_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['-date_created']},
        ),
    ]
