# Generated by Django 5.2.4 on 2025-07-27 10:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='Community',
            new_name='community',
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, populate_from='title', unique=True),
        ),
    ]
