# Generated by Django 5.2.4 on 2025-07-30 06:00

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_rename_community_topic_community_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, max_length=250, populate_from='title', unique=True),
        ),
    ]
